language: rust
rust:
  - 1.45.0
env:
  - RUST_BACKTRACE=1
addons:
  apt:
    packages: binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev ninja-build
before_install:
  - wget -O cmake.sh https://cmake.org/files/v3.13/cmake-3.13.3-Linux-x86_64.sh
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr
  - sudo rm -fR /usr/local/cmake*
  - hash -r
  - which cmake
  - cmake --version
  - curl -L https://github.com/mozilla/sccache/releases/download/0.2.8/sccache-0.2.8-x86_64-unknown-linux-musl.tar.gz | tar xvz
  - export PATH=$PATH:`pwd`/sccache-0.2.8-x86_64-unknown-linux-musl
  - export RUSTC_WRAPPER=sccache
  - export SCCACHE_CACHE_SIZE=500M
  - export SCCACHE_DIR=~/.cache/sccache
  - curl -L https://www.nasm.us/pub/nasm/releasebuilds/2.15.03/nasm-2.15.03.tar.gz | tar xvz
  - cd nasm-2.15.03
  - ./configure CC='sccache gcc' && make -j2 && sudo make install
  - nasm --version
  - cd ..

cache:
  directories:
    - "$HOME/.cache/sccache"

after_script:
  - sccache -s

jobs:
  include:
    - name: "Build"
      script:
        - cargo build --all --all-targets --verbose
