[package]
name = "revc"
version = "0.1.1"
authors = ["Rain Liu <yuliu@outlook.com>"]
edition = "2018"
description = "Rust Essential Video Coding (MPEG-5 EVC)"
license = "MIT"
documentation = "https://github.com/revcx/revc"
homepage = "https://github.com/revcx/revc"
repository = "https://github.com/revcx/revc"

[features]
binaries = [
    "clap",
]
default = ["binaries"]
ENC_DEC_TRACE = []
TRACE_HLS = ["ENC_DEC_TRACE"]

[dependencies]
arg_enum_proc_macro = "0.1.1"
bitstream-io = "0.8"
byteorder = "1.3.2"
clap = { version = "2", optional = true, default-features = false }
log = "0.4"
num-traits = "0.2"
num-derive = "0.3"

[[bin]]
name = "revcd"
path = "src/bin/revcd.rs"
required-features = ["binaries"]

[[bin]]
name = "revce"
path = "src/bin/revce.rs"
required-features = ["binaries"]
