name: revc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run decoder test
      run: |
        mkdir -p scripts/tmp
        cd scripts
        cargo run --bin revcd --release -- -i ./data/test_ra_b3_q37.evc -o ./tmp/test_ra_b3_q37_revc.yuv -v
        md5sum -c ./data/test_ra_b3_q37_yuv.txt
    - name: Run encoder test
      run: |
        mkdir -p scripts/tmp
        cd scripts
        cargo run --bin revce --release -- -i foreman_qcif8.yuv -w 176 -h 144 -z 30 -f 8 -q 37 -r ./tmp/test_ra_b3_q37_revc.yuv -o ./tmp/test_ra_b3_q37_revc.evc --max_b_frames 3 --inter_slice_type 0 -v
        md5sum -c ./data/test_ra_b3_q37_evc.txt
