name: revc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run decoder test
      run: |
        mkdir -p tools/tmp
        cd tools
        cargo run --bin revcd --release -- -i ./data/test_ra_b_q37.evc -o ./tmp/test_ra_b_q37_revc.yuv -v
        md5sum -c ./data/test_ra_b_q37.txt
    - name: Run encoder test
      run: |
        mkdir -p tools/tmp
        cd tools
        cargo run --bin revce --release -- -i ./foreman_qcif8.yuv -w 176 -h 144 -z 30 -f 8 -q 27 -r ./tmp/rec.yuv --keyint 1 --ref_pic_gap_length 8 --disable_dbf -o ./tmp/foreman_qcif8_nodb.evc -v
        md5sum -c ./data/foreman_qcif8_nodb.txt
